DEBUG|2021-03-15 17:34:24,955|LogManager(startElab:43)| backOffice.Loader: Elaboratione iniziata
DEBUG|2021-03-15 17:34:25,030|LogManager(EndElab:79)| backOffice.Loader: Elaboration in errore.Errore  durante l'inserimento massivo per la riga : - Messaggio d'errore: ERROR: relation "bo.tab_prova2" does not exist
